name: biometric_storage
description: Encrypted data store optionally secured by biometric lock with support for iOS, Android, MacOS aand Linux (Partial support).
version: 0.4.1
homepage: https://github.com/authpass/biometric_storage/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ">=0.10.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ">=1.7.0 <2.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: design.codeux.biometric_storage
        pluginClass: BiometricStoragePlugin
      ios:
        pluginClass: BiometricStoragePlugin
      macos:
        pluginClass: BiometricStorageMacOSPlugin
      linux:
        pluginClass: BiometricStoragePlugin

