name: biometric_storage
description: |
  Secure Storage: Encrypted data store optionally secured by biometric lock with support
  for iOS, Android, MacOS. Partial support for Linux, Windows and web (localStorage).
version: 2.0.3
homepage: https://github.com/authpass/biometric_storage/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  logging: ">=1.0.0 <2.0.0"
  plugin_platform_interface: ^2.0.0

  ffi: ^1.0.0
  win32: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: design.codeux.biometric_storage
        pluginClass: BiometricStoragePlugin
      ios:
        pluginClass: BiometricStoragePlugin
      macos:
        pluginClass: BiometricStorageMacOSPlugin
      linux:
        pluginClass: BiometricStoragePlugin
      windows:
        # TODO I don't think this is supported yet  https://github.com/flutter/flutter/issues/52267
        dartPluginClass: Win32BiometricStoragePlugin
        fileName: biometric_storage_win32.dart
        pluginClass: none
      web:
        pluginClass: BiometricStoragePluginWeb
        fileName: biometric_storage_web.dart
